<h2>numpy.insert的用法</h2>

numpy.insert可以有三个参数（arr，obj，values），也可以有4个参数（arr，obj，values，axis）：<br>
第一个参数arr是一个数组，可以是一维的也可以是多维的，在arr的基础上插入元素<br>
第二个参数obj是元素插入的位置<br>
第三个参数values是需要插入的数值<br>
第四个参数axis是指示在哪一个轴上对应的插入位置进行插入<br>

In [1]:
import numpy as np

In [2]:
array1 = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
array1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
np.insert(array1, 1, 10)

array([ 1, 10,  2,  3,  4,  5,  6])

<font color='red'>如果第四个参数没有给出，那么就默认为先对arr进行flatten操作，变为一维数组，然后再在对应的位置上插入对应的值。</font>

In [5]:
np.insert(array1, 1, 11, axis=1)

array([[ 1, 11,  2],
       [ 3, 11,  4],
       [ 5, 11,  6]])

在二维数组的某一列插入一个数，这个数会在该维度的每一个数组中都插入。

In [6]:
np.insert(array1, 1, [1, 2, 3], axis=1)

array([[1, 1, 2],
       [3, 2, 4],
       [5, 3, 6]])

<h2>应用：插值0</h2>

首先，产生一个随机数组

In [14]:
arr = np.random.randint(1, 10, size=10)

In [15]:
arr

array([1, 3, 6, 8, 3, 9, 9, 3, 9, 4])

插值（插0）操作是想在上述每个数值后面都插入0, 插入的0的个数由插值倍数决定

In [16]:
brr = arr.reshape(-1,1)

In [18]:
crr = np.insert(brr, 1, [[0], [0]], axis=1)

In [19]:
crr

array([[1, 0, 0],
       [3, 0, 0],
       [6, 0, 0],
       [8, 0, 0],
       [3, 0, 0],
       [9, 0, 0],
       [9, 0, 0],
       [3, 0, 0],
       [9, 0, 0],
       [4, 0, 0]])

In [20]:
crr.flatten()

array([1, 0, 0, 3, 0, 0, 6, 0, 0, 8, 0, 0, 3, 0, 0, 9, 0, 0, 9, 0, 0, 3,
       0, 0, 9, 0, 0, 4, 0, 0])